### ISSUE TITLE
Index of BCC checksum

### ISSUE THREAD

**Issue by linkmic** [priveros/Elster_A1100#2]
Hi!

I have been testing your code with my meter and am able to output the import / export values provided that the debug is turned on.

However, the BCC check seems to fail and I believe it is because I am receiving a longer message from the IrDA sensor than you were. Frame 328 may not contain the right BCC in fact. Do you recall how you went about locating the correct indexes for the different frames in the message or computing the total length of the message?

I'll carry on digging in the meanwhile, but if you have any thoughts/pointers you could share, I'd appreciate it.

/mike

**Comment by glynhudson** [comment]
Hi Mike, 

Sorry, I don't recall it's been a while since we worked on this. Please let us know how you get on. It would be good idea to post on our community forums to see if anyone else has had the same issue: https://community.openenergymonitor.org/

**Comment by linkmic** [comment]
Thanks for the quick reply. I'll post a solution / update to the different threads about this meter, if I find one. My meter is being swapped out next week, so test window is limited..

**Comment by priveros** [comment]
Hi Mike,

I have a new version of the code as I have implemented integrated to wifi reporting with a ESP8266. some parts have changed since. You would have to compare the code to find the differences and ignore all the RTC and Network stuff. Anyway, please have a look to the attachment.
[MeterReader_v1.zip](https://github.com/priveros/Elster_A1100/files/325436/MeterReader_v1.zip)

I have some spreadsheets I use to find out the bcc based on the output and also have some handwritten notes (pictures) I used to turn the period into binary. I also have a fritzing diagram of the wiring I did for the ESP and the RTC to the arduino for the attached code. Let me know if u are interested in any of those.

I move house so I no longer can test anything :(

Hope this help

Pedro

**Comment by linkmic** [comment]
Hi Pedro,

thanks for the note and the latest code. 

I was also thinking of using the ESP8266 if I was able to make things work satisfactorily on the regular Uno. Would appreciate any notes that you have or the spreadsheet that you used. 

I did a quick analysis of the string of measurement/pulse times that I received and believe that I get a message of a different length than you did, which would explain why the BCC is not found at Index 328. 

My existing one-way A1100 meter will be swapped out for a 4-quadrant / 2-way meter during next week. Hopefully they power company will carry on using the Elster A1100 series so this work can be reused.

/mike

**Comment by priveros** [comment]
Hi Mike, I'm in my way to work now, but later today I will create another repository here in will load all the files. Hopefully tonight, if life doesn't get in the way ;)  I'll try to get some word explaining each but probably would be very little. Just let me know if u have questions.

Cheers,

Pedro

**Comment by priveros** [comment]
Hi Mike, all files are in a new repository. Plase have a look. I'll close this issue now.

https://github.com/priveros/MeterReaderElsterA1100WIFI

**Comment by linkmic** [comment]
Just a note to say thanks for the extra docs. My power meter is being exchanged today, so this is the end of the road for this project for me. 

The only part of this code that does not work properly (for me, my Elster A1100C) is the checksum calculation and comparison.

For anyone looking here in the future, I got this working using a TSL 262 (http://ams.com/eng/Products/Light-Sensors/Light-to-Voltage/TSL262) and a 100kOhm pull up resistor.
